// Code generated by ent, DO NOT EDIT.
// --------------------------------------------------------------------
// SPDX-FileCopyrightText: Copyright © 2025 The DependencyTrack Authors
// SPDX-FileType: SOURCE
// SPDX-License-Identifier: Apache-2.0
// --------------------------------------------------------------------
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// --------------------------------------------------------------------

package ent

import (
	"context"

	"dependencytrack.io/hyades/ent/eventservicelog"
	"dependencytrack.io/hyades/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventServiceLogDelete is the builder for deleting a EventServiceLog entity.
type EventServiceLogDelete struct {
	config
	hooks    []Hook
	mutation *EventServiceLogMutation
}

// Where appends a list predicates to the EventServiceLogDelete builder.
func (esld *EventServiceLogDelete) Where(ps ...predicate.EventServiceLog) *EventServiceLogDelete {
	esld.mutation.Where(ps...)
	return esld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (esld *EventServiceLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, esld.sqlExec, esld.mutation, esld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (esld *EventServiceLogDelete) ExecX(ctx context.Context) int {
	n, err := esld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (esld *EventServiceLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(eventservicelog.Table, sqlgraph.NewFieldSpec(eventservicelog.FieldID, field.TypeInt))
	if ps := esld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, esld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	esld.mutation.done = true
	return affected, err
}

// EventServiceLogDeleteOne is the builder for deleting a single EventServiceLog entity.
type EventServiceLogDeleteOne struct {
	esld *EventServiceLogDelete
}

// Where appends a list predicates to the EventServiceLogDelete builder.
func (esldo *EventServiceLogDeleteOne) Where(ps ...predicate.EventServiceLog) *EventServiceLogDeleteOne {
	esldo.esld.mutation.Where(ps...)
	return esldo
}

// Exec executes the deletion query.
func (esldo *EventServiceLogDeleteOne) Exec(ctx context.Context) error {
	n, err := esldo.esld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eventservicelog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (esldo *EventServiceLogDeleteOne) ExecX(ctx context.Context) {
	if err := esldo.Exec(ctx); err != nil {
		panic(err)
	}
}
