// Code generated by ent, DO NOT EDIT.
// --------------------------------------------------------------------
// SPDX-FileCopyrightText: Copyright © 2025 The DependencyTrack Authors
// SPDX-FileType: SOURCE
// SPDX-License-Identifier: Apache-2.0
// --------------------------------------------------------------------
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// --------------------------------------------------------------------

package ent

import (
	"context"

	"dependencytrack.io/hyades/ent/installedupgrades"
	"dependencytrack.io/hyades/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// INSTALLEDUPGRADESDelete is the builder for deleting a INSTALLEDUPGRADES entity.
type INSTALLEDUPGRADESDelete struct {
	config
	hooks    []Hook
	mutation *INSTALLEDUPGRADESMutation
}

// Where appends a list predicates to the INSTALLEDUPGRADESDelete builder.
func (id *INSTALLEDUPGRADESDelete) Where(ps ...predicate.INSTALLEDUPGRADES) *INSTALLEDUPGRADESDelete {
	id.mutation.Where(ps...)
	return id
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (id *INSTALLEDUPGRADESDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, id.sqlExec, id.mutation, id.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (id *INSTALLEDUPGRADESDelete) ExecX(ctx context.Context) int {
	n, err := id.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (id *INSTALLEDUPGRADESDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(installedupgrades.Table, sqlgraph.NewFieldSpec(installedupgrades.FieldID, field.TypeInt))
	if ps := id.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, id.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	id.mutation.done = true
	return affected, err
}

// INSTALLEDUPGRADESDeleteOne is the builder for deleting a single INSTALLEDUPGRADES entity.
type INSTALLEDUPGRADESDeleteOne struct {
	id *INSTALLEDUPGRADESDelete
}

// Where appends a list predicates to the INSTALLEDUPGRADESDelete builder.
func (ido *INSTALLEDUPGRADESDeleteOne) Where(ps ...predicate.INSTALLEDUPGRADES) *INSTALLEDUPGRADESDeleteOne {
	ido.id.mutation.Where(ps...)
	return ido
}

// Exec executes the deletion query.
func (ido *INSTALLEDUPGRADESDeleteOne) Exec(ctx context.Context) error {
	n, err := ido.id.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{installedupgrades.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ido *INSTALLEDUPGRADESDeleteOne) ExecX(ctx context.Context) {
	if err := ido.Exec(ctx); err != nil {
		panic(err)
	}
}
