// Code generated by ent, DO NOT EDIT.
// --------------------------------------------------------------------
// SPDX-FileCopyrightText: Copyright © 2025 The DependencyTrack Authors
// SPDX-FileType: SOURCE
// SPDX-License-Identifier: Apache-2.0
// --------------------------------------------------------------------
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// --------------------------------------------------------------------

package ent

import (
	"context"

	"dependencytrack.io/hyades/ent/mappedldapgroup"
	"dependencytrack.io/hyades/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MappedLDAPGroupDelete is the builder for deleting a MappedLDAPGroup entity.
type MappedLDAPGroupDelete struct {
	config
	hooks    []Hook
	mutation *MappedLDAPGroupMutation
}

// Where appends a list predicates to the MappedLDAPGroupDelete builder.
func (mlgd *MappedLDAPGroupDelete) Where(ps ...predicate.MappedLDAPGroup) *MappedLDAPGroupDelete {
	mlgd.mutation.Where(ps...)
	return mlgd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mlgd *MappedLDAPGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mlgd.sqlExec, mlgd.mutation, mlgd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mlgd *MappedLDAPGroupDelete) ExecX(ctx context.Context) int {
	n, err := mlgd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mlgd *MappedLDAPGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mappedldapgroup.Table, sqlgraph.NewFieldSpec(mappedldapgroup.FieldID, field.TypeInt))
	if ps := mlgd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mlgd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mlgd.mutation.done = true
	return affected, err
}

// MappedLDAPGroupDeleteOne is the builder for deleting a single MappedLDAPGroup entity.
type MappedLDAPGroupDeleteOne struct {
	mlgd *MappedLDAPGroupDelete
}

// Where appends a list predicates to the MappedLDAPGroupDelete builder.
func (mlgdo *MappedLDAPGroupDeleteOne) Where(ps ...predicate.MappedLDAPGroup) *MappedLDAPGroupDeleteOne {
	mlgdo.mlgd.mutation.Where(ps...)
	return mlgdo
}

// Exec executes the deletion query.
func (mlgdo *MappedLDAPGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := mlgdo.mlgd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mappedldapgroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mlgdo *MappedLDAPGroupDeleteOne) ExecX(ctx context.Context) {
	if err := mlgdo.Exec(ctx); err != nil {
		panic(err)
	}
}
