// Code generated by ent, DO NOT EDIT.
// --------------------------------------------------------------------
// SPDX-FileCopyrightText: Copyright © 2025 The DependencyTrack Authors
// SPDX-FileType: SOURCE
// SPDX-License-Identifier: Apache-2.0
// --------------------------------------------------------------------
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// --------------------------------------------------------------------

package ent

import (
	"context"

	"dependencytrack.io/hyades/ent/mappedoidcgroup"
	"dependencytrack.io/hyades/ent/predicate"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MappedOIDCGroupDelete is the builder for deleting a MappedOIDCGroup entity.
type MappedOIDCGroupDelete struct {
	config
	hooks    []Hook
	mutation *MappedOIDCGroupMutation
}

// Where appends a list predicates to the MappedOIDCGroupDelete builder.
func (mogd *MappedOIDCGroupDelete) Where(ps ...predicate.MappedOIDCGroup) *MappedOIDCGroupDelete {
	mogd.mutation.Where(ps...)
	return mogd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mogd *MappedOIDCGroupDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mogd.sqlExec, mogd.mutation, mogd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mogd *MappedOIDCGroupDelete) ExecX(ctx context.Context) int {
	n, err := mogd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mogd *MappedOIDCGroupDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mappedoidcgroup.Table, sqlgraph.NewFieldSpec(mappedoidcgroup.FieldID, field.TypeInt))
	if ps := mogd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mogd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mogd.mutation.done = true
	return affected, err
}

// MappedOIDCGroupDeleteOne is the builder for deleting a single MappedOIDCGroup entity.
type MappedOIDCGroupDeleteOne struct {
	mogd *MappedOIDCGroupDelete
}

// Where appends a list predicates to the MappedOIDCGroupDelete builder.
func (mogdo *MappedOIDCGroupDeleteOne) Where(ps ...predicate.MappedOIDCGroup) *MappedOIDCGroupDeleteOne {
	mogdo.mogd.mutation.Where(ps...)
	return mogdo
}

// Exec executes the deletion query.
func (mogdo *MappedOIDCGroupDeleteOne) Exec(ctx context.Context) error {
	n, err := mogdo.mogd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mappedoidcgroup.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mogdo *MappedOIDCGroupDeleteOne) ExecX(ctx context.Context) {
	if err := mogdo.Exec(ctx); err != nil {
		panic(err)
	}
}
