// Code generated by ent, DO NOT EDIT.
// --------------------------------------------------------------------
// SPDX-FileCopyrightText: Copyright © 2025 The DependencyTrack Authors
// SPDX-FileType: SOURCE
// SPDX-License-Identifier: Apache-2.0
// --------------------------------------------------------------------
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// --------------------------------------------------------------------

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"dependencytrack.io/hyades/ent/oidcgroup"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// OIDCGroup is the model entity for the OIDCGroup schema.
type OIDCGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UUID holds the value of the "uuid" field.
	UUID uuid.UUID `json:"uuid,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OIDCGroupQuery when eager-loading is set.
	Edges        OIDCGroupEdges `json:"-"`
	selectValues sql.SelectValues
}

// OIDCGroupEdges holds the relations/edges for other nodes in the graph.
type OIDCGroupEdges struct {
	// MappedOidcGroups holds the value of the mapped_oidc_groups edge.
	MappedOidcGroups []*MappedOIDCGroup `json:"mapped_oidc_groups,omitempty"`
	// Team holds the value of the team edge.
	Team []*Team `json:"-"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MappedOidcGroupsOrErr returns the MappedOidcGroups value or an error if the edge
// was not loaded in eager-loading.
func (e OIDCGroupEdges) MappedOidcGroupsOrErr() ([]*MappedOIDCGroup, error) {
	if e.loadedTypes[0] {
		return e.MappedOidcGroups, nil
	}
	return nil, &NotLoadedError{edge: "mapped_oidc_groups"}
}

// TeamOrErr returns the Team value or an error if the edge
// was not loaded in eager-loading.
func (e OIDCGroupEdges) TeamOrErr() ([]*Team, error) {
	if e.loadedTypes[1] {
		return e.Team, nil
	}
	return nil, &NotLoadedError{edge: "team"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OIDCGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oidcgroup.FieldID:
			values[i] = new(sql.NullInt64)
		case oidcgroup.FieldName:
			values[i] = new(sql.NullString)
		case oidcgroup.FieldUUID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OIDCGroup fields.
func (og *OIDCGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oidcgroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			og.ID = int(value.Int64)
		case oidcgroup.FieldUUID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field uuid", values[i])
			} else if value != nil {
				og.UUID = *value
			}
		case oidcgroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				og.Name = value.String
			}
		default:
			og.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OIDCGroup.
// This includes values selected through modifiers, order, etc.
func (og *OIDCGroup) Value(name string) (ent.Value, error) {
	return og.selectValues.Get(name)
}

// QueryMappedOidcGroups queries the "mapped_oidc_groups" edge of the OIDCGroup entity.
func (og *OIDCGroup) QueryMappedOidcGroups() *MappedOIDCGroupQuery {
	return NewOIDCGroupClient(og.config).QueryMappedOidcGroups(og)
}

// QueryTeam queries the "team" edge of the OIDCGroup entity.
func (og *OIDCGroup) QueryTeam() *TeamQuery {
	return NewOIDCGroupClient(og.config).QueryTeam(og)
}

// Update returns a builder for updating this OIDCGroup.
// Note that you need to call OIDCGroup.Unwrap() before calling this method if this OIDCGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (og *OIDCGroup) Update() *OIDCGroupUpdateOne {
	return NewOIDCGroupClient(og.config).UpdateOne(og)
}

// Unwrap unwraps the OIDCGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (og *OIDCGroup) Unwrap() *OIDCGroup {
	_tx, ok := og.config.driver.(*txDriver)
	if !ok {
		panic("ent: OIDCGroup is not a transactional entity")
	}
	og.config.driver = _tx.drv
	return og
}

// String implements the fmt.Stringer.
func (og *OIDCGroup) String() string {
	var builder strings.Builder
	builder.WriteString("OIDCGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", og.ID))
	builder.WriteString("uuid=")
	builder.WriteString(fmt.Sprintf("%v", og.UUID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(og.Name)
	builder.WriteByte(')')
	return builder.String()
}

// MarshalJSON implements the json.Marshaler interface.
func (og *OIDCGroup) MarshalJSON() ([]byte, error) {
	type Alias OIDCGroup
	return json.Marshal(&struct {
		*Alias
		OIDCGroupEdges
	}{
		Alias:          (*Alias)(og),
		OIDCGroupEdges: og.Edges,
	})
}

// OIDCGroups is a parsable slice of OIDCGroup.
type OIDCGroups []*OIDCGroup
