// Code generated by ent, DO NOT EDIT.
// --------------------------------------------------------------------
// SPDX-FileCopyrightText: Copyright © 2025 The DependencyTrack Authors
// SPDX-FileType: SOURCE
// SPDX-License-Identifier: Apache-2.0
// --------------------------------------------------------------------
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// --------------------------------------------------------------------

package ent

import (
	"context"
	"fmt"
	"math"

	"dependencytrack.io/hyades/ent/predicate"
	"dependencytrack.io/hyades/ent/schemaversion"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SchemaVersionQuery is the builder for querying SchemaVersion entities.
type SchemaVersionQuery struct {
	config
	ctx        *QueryContext
	order      []schemaversion.OrderOption
	inters     []Interceptor
	predicates []predicate.SchemaVersion
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SchemaVersionQuery builder.
func (svq *SchemaVersionQuery) Where(ps ...predicate.SchemaVersion) *SchemaVersionQuery {
	svq.predicates = append(svq.predicates, ps...)
	return svq
}

// Limit the number of records to be returned by this query.
func (svq *SchemaVersionQuery) Limit(limit int) *SchemaVersionQuery {
	svq.ctx.Limit = &limit
	return svq
}

// Offset to start from.
func (svq *SchemaVersionQuery) Offset(offset int) *SchemaVersionQuery {
	svq.ctx.Offset = &offset
	return svq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (svq *SchemaVersionQuery) Unique(unique bool) *SchemaVersionQuery {
	svq.ctx.Unique = &unique
	return svq
}

// Order specifies how the records should be ordered.
func (svq *SchemaVersionQuery) Order(o ...schemaversion.OrderOption) *SchemaVersionQuery {
	svq.order = append(svq.order, o...)
	return svq
}

// First returns the first SchemaVersion entity from the query.
// Returns a *NotFoundError when no SchemaVersion was found.
func (svq *SchemaVersionQuery) First(ctx context.Context) (*SchemaVersion, error) {
	nodes, err := svq.Limit(1).All(setContextOp(ctx, svq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{schemaversion.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (svq *SchemaVersionQuery) FirstX(ctx context.Context) *SchemaVersion {
	node, err := svq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SchemaVersion ID from the query.
// Returns a *NotFoundError when no SchemaVersion ID was found.
func (svq *SchemaVersionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = svq.Limit(1).IDs(setContextOp(ctx, svq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{schemaversion.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (svq *SchemaVersionQuery) FirstIDX(ctx context.Context) int {
	id, err := svq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SchemaVersion entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SchemaVersion entity is found.
// Returns a *NotFoundError when no SchemaVersion entities are found.
func (svq *SchemaVersionQuery) Only(ctx context.Context) (*SchemaVersion, error) {
	nodes, err := svq.Limit(2).All(setContextOp(ctx, svq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{schemaversion.Label}
	default:
		return nil, &NotSingularError{schemaversion.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (svq *SchemaVersionQuery) OnlyX(ctx context.Context) *SchemaVersion {
	node, err := svq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SchemaVersion ID in the query.
// Returns a *NotSingularError when more than one SchemaVersion ID is found.
// Returns a *NotFoundError when no entities are found.
func (svq *SchemaVersionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = svq.Limit(2).IDs(setContextOp(ctx, svq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{schemaversion.Label}
	default:
		err = &NotSingularError{schemaversion.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (svq *SchemaVersionQuery) OnlyIDX(ctx context.Context) int {
	id, err := svq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SchemaVersions.
func (svq *SchemaVersionQuery) All(ctx context.Context) ([]*SchemaVersion, error) {
	ctx = setContextOp(ctx, svq.ctx, ent.OpQueryAll)
	if err := svq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SchemaVersion, *SchemaVersionQuery]()
	return withInterceptors[[]*SchemaVersion](ctx, svq, qr, svq.inters)
}

// AllX is like All, but panics if an error occurs.
func (svq *SchemaVersionQuery) AllX(ctx context.Context) []*SchemaVersion {
	nodes, err := svq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SchemaVersion IDs.
func (svq *SchemaVersionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if svq.ctx.Unique == nil && svq.path != nil {
		svq.Unique(true)
	}
	ctx = setContextOp(ctx, svq.ctx, ent.OpQueryIDs)
	if err = svq.Select(schemaversion.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (svq *SchemaVersionQuery) IDsX(ctx context.Context) []int {
	ids, err := svq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (svq *SchemaVersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, svq.ctx, ent.OpQueryCount)
	if err := svq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, svq, querierCount[*SchemaVersionQuery](), svq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (svq *SchemaVersionQuery) CountX(ctx context.Context) int {
	count, err := svq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (svq *SchemaVersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, svq.ctx, ent.OpQueryExist)
	switch _, err := svq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (svq *SchemaVersionQuery) ExistX(ctx context.Context) bool {
	exist, err := svq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SchemaVersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (svq *SchemaVersionQuery) Clone() *SchemaVersionQuery {
	if svq == nil {
		return nil
	}
	return &SchemaVersionQuery{
		config:     svq.config,
		ctx:        svq.ctx.Clone(),
		order:      append([]schemaversion.OrderOption{}, svq.order...),
		inters:     append([]Interceptor{}, svq.inters...),
		predicates: append([]predicate.SchemaVersion{}, svq.predicates...),
		// clone intermediate query.
		sql:  svq.sql.Clone(),
		path: svq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Version string `json:"version,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SchemaVersion.Query().
//		GroupBy(schemaversion.FieldVersion).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (svq *SchemaVersionQuery) GroupBy(field string, fields ...string) *SchemaVersionGroupBy {
	svq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SchemaVersionGroupBy{build: svq}
	grbuild.flds = &svq.ctx.Fields
	grbuild.label = schemaversion.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Version string `json:"version,omitempty"`
//	}
//
//	client.SchemaVersion.Query().
//		Select(schemaversion.FieldVersion).
//		Scan(ctx, &v)
func (svq *SchemaVersionQuery) Select(fields ...string) *SchemaVersionSelect {
	svq.ctx.Fields = append(svq.ctx.Fields, fields...)
	sbuild := &SchemaVersionSelect{SchemaVersionQuery: svq}
	sbuild.label = schemaversion.Label
	sbuild.flds, sbuild.scan = &svq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SchemaVersionSelect configured with the given aggregations.
func (svq *SchemaVersionQuery) Aggregate(fns ...AggregateFunc) *SchemaVersionSelect {
	return svq.Select().Aggregate(fns...)
}

func (svq *SchemaVersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range svq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, svq); err != nil {
				return err
			}
		}
	}
	for _, f := range svq.ctx.Fields {
		if !schemaversion.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if svq.path != nil {
		prev, err := svq.path(ctx)
		if err != nil {
			return err
		}
		svq.sql = prev
	}
	return nil
}

func (svq *SchemaVersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SchemaVersion, error) {
	var (
		nodes = []*SchemaVersion{}
		_spec = svq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SchemaVersion).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SchemaVersion{config: svq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, svq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (svq *SchemaVersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := svq.querySpec()
	_spec.Node.Columns = svq.ctx.Fields
	if len(svq.ctx.Fields) > 0 {
		_spec.Unique = svq.ctx.Unique != nil && *svq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, svq.driver, _spec)
}

func (svq *SchemaVersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(schemaversion.Table, schemaversion.Columns, sqlgraph.NewFieldSpec(schemaversion.FieldID, field.TypeInt))
	_spec.From = svq.sql
	if unique := svq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if svq.path != nil {
		_spec.Unique = true
	}
	if fields := svq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schemaversion.FieldID)
		for i := range fields {
			if fields[i] != schemaversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := svq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := svq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := svq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := svq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (svq *SchemaVersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(svq.driver.Dialect())
	t1 := builder.Table(schemaversion.Table)
	columns := svq.ctx.Fields
	if len(columns) == 0 {
		columns = schemaversion.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if svq.sql != nil {
		selector = svq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if svq.ctx.Unique != nil && *svq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range svq.predicates {
		p(selector)
	}
	for _, p := range svq.order {
		p(selector)
	}
	if offset := svq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := svq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SchemaVersionGroupBy is the group-by builder for SchemaVersion entities.
type SchemaVersionGroupBy struct {
	selector
	build *SchemaVersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (svgb *SchemaVersionGroupBy) Aggregate(fns ...AggregateFunc) *SchemaVersionGroupBy {
	svgb.fns = append(svgb.fns, fns...)
	return svgb
}

// Scan applies the selector query and scans the result into the given value.
func (svgb *SchemaVersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, svgb.build.ctx, ent.OpQueryGroupBy)
	if err := svgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SchemaVersionQuery, *SchemaVersionGroupBy](ctx, svgb.build, svgb, svgb.build.inters, v)
}

func (svgb *SchemaVersionGroupBy) sqlScan(ctx context.Context, root *SchemaVersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(svgb.fns))
	for _, fn := range svgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*svgb.flds)+len(svgb.fns))
		for _, f := range *svgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*svgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SchemaVersionSelect is the builder for selecting fields of SchemaVersion entities.
type SchemaVersionSelect struct {
	*SchemaVersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (svs *SchemaVersionSelect) Aggregate(fns ...AggregateFunc) *SchemaVersionSelect {
	svs.fns = append(svs.fns, fns...)
	return svs
}

// Scan applies the selector query and scans the result into the given value.
func (svs *SchemaVersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, svs.ctx, ent.OpQuerySelect)
	if err := svs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SchemaVersionQuery, *SchemaVersionSelect](ctx, svs.SchemaVersionQuery, svs, svs.inters, v)
}

func (svs *SchemaVersionSelect) sqlScan(ctx context.Context, root *SchemaVersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(svs.fns))
	for _, fn := range svs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*svs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := svs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
